
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mytube-bmeznar_development

test:
  <<: *default
  database: mytube-bmeznar_test

production:
  <<: *default
  database: mytube-bmeznar_production
  username: mytube-bmeznar
  password: <%= ENV['MYTUBE-BMEZNAR_DATABASE_PASSWORD'] %>
